name: hf
plugins:
    - name: infura
    - name: alchemy
    - name: solidity
ethereum:
  mainnet:
    default_provider: alchemy
  mainnet_fork:
    default_provider: foundry

foundry:
  fork:
    ethereum:
      mainnet_fork:
        upstream_provider: alchemy
